export enum Actions {
  SET_LOADER_ON = 'SET_LOADER_ON',
  SET_LOADER_OFF = 'SET_LOADER_OFF',
  OPEN_MODAL = 'OPEN_MODAL',
  CLOSE_MODAL = 'CLOSE_MODAL',
  OPEN_FORM_MODAL = 'OPEN_FORM_MODAL',
  CLOSE_FORM_MODAL = 'CLOSE_FORM_MODAL',
  OPEN_CONFIRMATION_MSG_MODAL = 'OPEN_CONFIRMATION_MSG_MODAL',
  CLOSE_CONFIRMATION_MSG_MODAL = 'CLOSE_CONFIRMATION_MSG_MODAL',
  OPEN_LOGOUT_MODAL = 'OPEN_LOGOUT_MODAL',
  CLOSE_LOGOUT_MODAL = 'CLOSE_LOGOUT_MODAL',
}
