export enum Actions {
  ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS',
  ADD_MEMBER_PENDING = 'ADD_MEMBER_PENDING',
  ADD_MEMBER_ERROR = 'ADD_MEMBER_ERROR',
  DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS',
  DELETE_MEMBER_PENDING = 'DELETE_MEMBER_PENDING',
  DELETE_MEMBER_ERROR = 'DELETE_MEMBER_ERROR',
}
