export enum Actions {
  GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS',
  GET_CLIENTS_PENDING = 'GET_CLIENTS_PENDING',
  GET_CLIENTS_ERROR = 'GET_CLIENTS_ERROR',
  DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS',
  DELETE_CLIENT_PENDING = 'DELETE_CLIENT_PENDING',
  DELETE_CLIENT_ERROR = 'DELETE_CLIENT_ERROR',
}
