export enum Actions {
  GET_EMPLOYEE_PENDING = 'GET_EMPLOYEE_PENDING',
  GET_EMPLOYEE_SUCCESS = 'GET_EMPLOYEE_SUCCESS',
  GET_EMPLOYEE_ERROR = 'GET_EMPLOYEE_ERROR',
  EDIT_EMPLOYEE_PENDING = 'EDIT_EMPLOYEE_PENDING',
  EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS',
  EDIT_EMPLOYEE_ERROR = 'EDIT_EMPLOYEE_ERROR',
}
