export enum Actions {
  GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS',
  GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING',
  GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR',
  ADD_PROJECT_SUCCESS = 'ADD_PROJECTS_SUCCESS',
  ADD_PROJECT_PENDING = 'ADD_PROJECTS_PENDING',
  ADD_PROJECT_ERROR = 'ADD_PROJECTS_ERROR',
  EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS',
  EDIT_PROJECT_PENDING = 'EDIT_PROJECT_PENDING',
  EDIT_PROJECT_ERROR = 'EDIT_PROJECT_ERROR',
  DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS',
  DELETE_PROJECT_PENDING = 'DELETE_PROJECT_PENDING',
  DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR',
}
