export enum Actions {
  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
  GET_USERS_PENDING = 'GET_USERS_PENDING',
  GET_USERS_ERROR = 'GET_USERS_ERROR',
  ADD_USER_SUCCESS = 'ADD_USERS_SUCCESS',
  ADD_USER_PENDING = 'ADD_USERS_PENDING',
  ADD_USER_ERROR = 'ADD_USERS_ERROR',
  EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS',
  EDIT_USER_PENDING = 'EDIT_USER_PENDING',
  EDIT_USER_ERROR = 'EDIT_USER_ERROR',
}
